# Generated by Django 6.0.4 on 2026-04-13 14:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('permissions', models.CharField(default='full', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(default='Свободен', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('is_available', models.BooleanField(default=True)),
                ('unit', models.CharField(default='шт', max_length=20)),
                ('category', models.CharField(choices=[('base', 'Основа'), ('sauce', 'Соус'), ('cheese', 'Сыр'), ('topping', 'Топпинг')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CustomPizza',
            fields=[
                ('custom_pizza_id', models.AutoField(primary_key=True, serialize=False)),
                ('custom_price', models.FloatField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.client')),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_pizzas', to='pizza.ingredient')),
                ('cheese', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheese_pizzas', to='pizza.ingredient')),
                ('sauce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sauce_pizzas', to='pizza.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPizzaIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.custompizza')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Принят', 'Принят'), ('Готовится', 'Готовится'), ('В печи', 'В печи'), ('Передан курьеру', 'Передан курьеру'), ('Доставлен', 'Доставлен')], default='Принят', max_length=50)),
                ('delivery_type', models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], max_length=20)),
                ('amount', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.client')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizza.courier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('status_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.order')),
            ],
        ),
    ]
