# Generated by Django 5.1.7 on 2026-04-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_pizza_alter_custompizzaingredient_id_cartitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Готовится', 'Готовится'), ('В печи', 'В печи'), ('Передан курьеру', 'Передан курьеру'), ('Доставлен', 'Доставлен'), ('Отменен', 'Отменен')], default='Принят', max_length=50),
        ),
    ]
